# Generated by Django 5.0.4 on 2024-04-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='option_text',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=''),
        ),
    ]
