# Generated by Django 5.0.4 on 2024-04-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_option_option_option_option_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option',
        ),
    ]
