# Generated by Django 5.0.4 on 2024-04-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_remove_option_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
