# Generated by Django 5.0.4 on 2024-04-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_question_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(max_length=200),
        ),
    ]
