# Generated by Django 5.0.4 on 2024-04-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_remove_question_question_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
