# Generated by Django 5.0.4 on 2024-04-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_remove_question_id_question_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question',
            new_name='question_id',
        ),
    ]
