# Generated by Django 5.0.4 on 2024-04-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_rename_question_option_question_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
