# Generated by Django 5.0.4 on 2024-04-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
