# Generated by Django 5.0.4 on 2024-04-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_rename_option_option_option_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
    ]
